name: MacOS-CI

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  testflight:
    env:
      APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}
      FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
      FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
      FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
      FLUTTER_BUILD_NUMBER: ${{ secrets.FLUTTER_BUILD_NUMBER }}
      FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
      MATCH_REPO: ${{ secrets.MATCH_REPO }}
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
      TEAM_ID: ${{ secrets.TEAM_ID }}
    runs-on: macos-latest
    if: contains(github.ref, 'tags')
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '8.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'

      - name: Change flutter channel to master, enable macos support
        run: |
          flutter channel master
          flutter upgrade
          flutter config --enable-macos-desktop
          flutter pub get

      - name: Build ios 
        run: |
          flutter build ios --release --no-codesign
      
      - name: Run fastlane setup
        run: |
          cd ios
          fastlane setup --verbose

      - name: Run fastlane build
        run: |
          cd ios
          fastlane compile --verbose

      - name: Run fastlane deploy
        run: |
          cd ios
          fastlane deploy --verbose
